### ISSUE TITLE
resizing the bottombar

### ISSUE THREAD

**Issue by Boxroma** [ssyandroid/bottombar_lib#1]
is it possible to resize the height of the bottombar??

**Comment by Boxroma** [comment]
@ssyandroid

**Comment by ssyandroid** [comment]
You should look at the author's BottomBar library for Android.
 Iiro Krankka (https://github.com/roughike/BottomBar).
@Boxroma

**Comment by Boxroma** [comment]
aite thanks!! @ssyandroid
